#+title: Logika - notatka pomocnicza do ćwiczeń
#+AUTHOR: JJS
#+OPTIONS: tex:t
#+LANGUAGE: pl
#+STARTUP: latexpreview

* Zajęcia 1 - Wprowadzenie
** Sprawy formalne i organizacyjne
1) warunki zaliczenia
2) dyżur
3) podręczniki
   a) Literatura obowiązkowa:
      - Z. Ziembiński, Logika Praktyczna, Warszawa 2004.
      - T. Bekrycht, Logiczne podstawy prawoznawstwa, Warszawa 2010, https://www.academia.edu/21615638/LOGIKA_skrypt_Bekrycht.
   b) Literatura uzupełniająca:
      - A. Malinowski, S. Lewandowski, H. Machińska J. Petzel, Logika dla Prawników, Warszawa 2009
      - J. Stelmach, B. Brożek, Metody Prawnicze, rozdziały I, II, III pkt. 1-2.

*** Przerwy
5-10 minut - na wniosek grupy

*** Nieobecności
Dopuszczalne dwie nieobecności. Nieobecność ponad dwie nieobecności należy zaliczyć na dyżurze w ciągu dwóch tygodni od wystąpienia nieobecności.

** Wprowadzenie
Dlaczego to jest śmieszne:

/Trzech logików wchodzi do baru. Barman pyta: „Czy wszyscy chcecie piwo?” Odpowiadają po kolei: 1: Nie wiem, 2: Nie wiem, 3. Tak./

*Logika* – nauka o sposobach jasnego i ścisłego formułowania myśli, o regułach poprawnego rozumowania i uzasadniania twierdzeń.

** Kategorie syntaktyczne
a. Zdania, nazwy i funktory.
b. Zdanie jest całkowicie samodzielną kategorią języka opisowego. Zdanie głosi więc, że jest tak a tak: /Granit jest skałą magmową. Sędzia opuścił salę rozpraw./
c. Nazwa — coś co nadaje się na podmiot lub na orzecznik orzeczenia imiennego w zdaniu: /prawnik, planeta, sędzia/.
d. Funktor to wyraz lub wyrażenie (leks), które nie jest ani nazwą, ani zdaniem, ale w połączeniu z nimi tworzy bardziej złożoną całość.
e. Funktory dzielimy na zdaniotwórcze, nazwotwórcze i funktorotwórcze. Wyrazy lub wyrażenia, które funktor wiąże w większą całość, nazywamy argumentami funktora.

Zdania oznacza się symbolicznie /z/. Nazwy oznacza się symbolicznie /n/.

Przykłady funktorów:

a. funktor nazwotwórczy od (jednego) argumentu nazwowego: /zielona/ gęś: \(\frac{n}{n}\)
b. funktor nazwotwórczy od dwóch argumentów nazwowych: most /nad/ rzeką: \(\frac{n}{nn}\)
c. funktor zdaniotwórczy od argumentu nazwowego: sędzia /śpi/: \(\frac{z}{n}\)
d. funktor zdaniotwórczy od dwóch argumentów zdaniowych: /chociaż/ w Warszawie pada deszcz /to/ w Łodzi świeci słońce: \(\frac{z}{zz}\)
e. funktor funktorotwórczy od argumentu funktorowego: sędzia (/n/) /głęboko/ śpi \(\frac{z}{n}\) : Czym zatem, jest słowo /głęboko/? Tym: \(\frac{\frac{z}{n}}{\frac{z}{n}}\)

Zastępowalność wyrażeń w tej samej kategorii syntaktycznej. Przykłady:

a. Sędzia głęboko śpi. Sędzia głęboko słucha.
b. Piękna melodia. Zielona melodia.
c. Rdza niszczy metal. Rdza podziwia metal.

Ale już nie: /zielona/ gęś \rarr  /nad/ gęś

**** Zadanie — określ kategorie syntaktyczne w zdaniu
***** Przykład 1
a) Sędzia \(\type{n}\)
b) przesłuchuje \(\frac{z}{nn}\)
c) świadka. \(\type{n}\)

***** Przykład 2
a) Nieprawda, że \(\frac{z}{z}\)
b) świeci \(\frac{z}{n}\)
c) słońce. \(\type{n}\)

** Role semiotyczne wypowiedzi

**** Rola opisowa

Wypowiedź opisuje rzeczywistość.

a. Świeci słońce.
b. W lipcu w Polsce jest zima.

**** Rola ekspresywna

Komunikuje przeżycia, przemyślenia, stan wewnętrzny.

a. Moja poranna kawa była ekstatycznie smaczna!
b. Ach, świeci słońce!
c. Ten obraz jest przepiękny.

**** Rola sugestywna

Ma wywołać w odbiorcy komunikatu jakieś zachowanie.

a. Janku, o godz. 9 masz być w łóżku!
b. Nie jestem pewien, że podoba mi się ta twoja nowa koszulka.
c. Ta dziewczyna puściła do Ciebie oczko.
d. Kto przekracza dozwoloną prędkość podlega karze…
e. Palenie zabija!

**** Rola performatywna

Wypowiedź wywołuje skutki konwencjonalne.

Jan wypowiedział słowa przysięgi małżeńskiej wobec Małgosi, ale nie doszło do zawarcia małżeństwa; Małgosia również wypowiedziała odpowiednie słowa, nadal nie doszło do zawarcia małżeństwa. Dlaczego? Pomysł 1: nie byli uprawnieni do zawarcia małżeństwa; pomysł 2: wypowiedzi były nie na serio (np. aktorzy); pomysł 3: brak urzędnika albo świadków.

a. Złożenie przysięgi lub ślubowania.
b. Nakładam na Pana mandat karny w wysokości 500 zł.

   
** Do przeczytania
Rozdział 1 z podręcznika Z. Ziembińskiego

* Zajęcia 2 - Ogólne wiadomości o języku (ciąg dalszy)

* Zajęcia 3 - Nazwy
 
