#+TITLE: Logika
#+SUBTITLE: Skrypt dla studentów prawa napisany w prostym języku
#+AUTHOR: Jakub J. Szczerbowski
#+OPTIONS: tex:nil
#+DATE: wersja 0.1
#+LANGUAGE: pl 
#+LATEX_CLASS: article
#+STARTUP: fninline

* TODO Wprowadzenie
** Jak korzystać z tego skryptu?
- Niniejszy dokument występuje w dwóch wersjach źródłowej używającej składni org-mode (https://orgmode.org/), zawartej w pliku =.org= oraz w wersji wynikowej: =.pdf=.
- Wersję źródłową (=.org=) można czytać przy pomocy dowolnego edytora tekstu. Zalecanym jest Emacs (https://www.gnu.org/software/emacs/), który obsługuje org-mode. Inne edytory mogą lepiej wyświetlać pliki =.org= jeśli zainstalujesz odpowiednią wtyczkę lub rozszerzenie.
- Korzystaj z aktualnej wersji tego dokumentu, którą możesz znaleźć na stronie https://github.com/szczerbowski/dydaktyka/blob/master/logika-skrypt.org

** Co to jest prosty język?
Prosty język to styl pisania zaprojektowany tak, aby czytelnik mógł zrozumieć tekst tak

- szybko
- łatwo
- kompletenie

jak tylko to możliwe. 
* TODO Ogólne wiadomości o logice i języku
** Znak i kategorie syntaktyczne
Semiotyka (ogólna nauka o znakach): (1) semantyka — nauka o stosunku pomiędzy
znakiem a tym do czego znak się odnosi; (2) syntaktyka — nauka o rodzajach
znaków i regułach wiązania ich w znaki złożone; (3) nauka zajmująca się
zagadnieniami stosunków pomiędzy znakami a wypowiadającym je lub odbierającym
człowiekiem.

Logika a prawda. Co to jest prawda? Co to jest zdanie prawdziwe? Czy każde
zdanie może być prawdziwe?

Logika formalna zajmuje się poprawnymi rozumowaniami.

*** Przykłady zdań
- Studenci uczą się pilnie.
- Warszawa jest stolicą Polski.
- Robert: W połowie drogi mojego żywota pośród ciemnego znalazłem się lasu.
- Stateczny, pulchny Buck Mulligan wynurzył się z wylotu schodów, niosąc mydlaną pianę w miseczce, na której leżały skrzyżowane lusterko i brzytwa.
- Wrzątek zawsze jest gorący.
- Ziemia jest płaska.
- Słońce świeci nocą.
- W konkursie chopinowskim wygrał najlepszy pianista.
- Gdzie leży mój długopis? - nie jest to zdanie w sensie logicznym
- Trójkąt ma cztery boki.
- Siedzę na niebieskim fotelu.

*** Znak
- *Pojęcie znaku* - układ rzeczy + reguły znaczeniowe.
- Czy zawsze są to znaki słowne?
- Znaczenie kontekstu: biała flaga, podanie ręki a umowa, przysięga małżeńska.
- Znak a symptom, objaw — jest to coś innego.
- Język — system obejmujący zbiór znaków słownych. Istnieją języki naturalne i języki sztuczne. Żargon — w tym żargon prawniczy: domieszka do języka naturalnego.
- W różnych językach słowa mogą mieć to samo znaczenie i brzmieć inaczej, albo na odwrót.
- Naturalnie powstają nowe słowa oraz nowe znaczenia (np. nowe znaczenie słowa /dzban/).
- Język wyróżnia zarówno zasób słów, jak i jego składnia. Istnieją nieprzetłumaczalne wprost zwroty.
- Język prawny a język prawniczy.

*** Metajęzyk
**** Przykład
#+begin_center
1. /Zdanie poniżej jest prawdziwe./

2. /Zdanie powyżej jest fałszywe./
#+end_center

**** Wyjaśnienie
a. Metajęzyk: język, który mówi o języku.
b. Wypowiedź w języku pierwszego stopnia (języku przedmiotowym): /Pada deszcz./
c. Wypowiedź w języku drugiego stopnia (metajęzyku w stosunku do języka
   pierwszego stopnia): /Jan powiedział, że pada deszcz./
d. Wypowiedź w języku trzeciego stopnia (metajęzyku w stosunku do języka
   drugiego stopnia): /Marcin powiedział, że Jan powiedział, że pada deszcz./

*** Kategorie syntaktyczne
a. Zdania, nazwy i funktory.
b. Zdanie jest całkowicie samodzielną kategorią języka opisowego. Zdanie głosi
   więc, że jest tak a tak: /Granit jest skałą magmową. Sędzia opuścił salę
   rozpraw./
c. Nazwa — coś co nadaje się na podmiot lub na orzecznik orzeczenia imiennego
   w zdaniu: /prawnik, planeta, sędzia/.
d. Funktor to wyraz lub wyrażenie (leks), które nie jest ani nazwą, ani zdaniem,
   ale w połączeniu z nimi tworzy bardziej złożoną całość.
e. Funktory dzielimy na zdaniotwórcze, nazwotwórcze i funktorotwórcze. Wyrazy
   lub wyrażenia, które funktor wiąże w większą całość, nazywamy argumentami
   funktora.

Zdania oznacza się symbolicznie /z/. Nazwy oznacza się symbolicznie /n/.

Przykłady funktorów:

a. funktor nazwotwórczy od (jednego) argumentu nazwowego: /zielona/ gęś:
   \(\frac{n}{n}\)
b. funktor nazwotwórczy od dwóch argumentów nazwowych: most /nad/ rzeką:
   \(\frac{n}{nn}\)
c. funktor zdaniotwórczy od argumentu nazwowego: sędzia /śpi/: \(\frac{z}{n}\)
d. funktor zdaniotwórczy od dwóch argumentów zdaniowych: /chociaż/ w Warszawie
   pada deszcz /to/ w Łodzi świeci słońce: \(\frac{z}{zz}\)
e. funktor funktorotwórczy od argumentu funktorowego: sędzia (/n/) /głęboko/ śpi
   \(\frac{z}{n}\) : Czym zatem, jest słowo /głęboko/? Tym:  \(\frac{\frac{z}{n}}{\frac{z}{n}}\)

Zastępowalność wyrażeń w tej samej kategorii syntaktycznej. Przykłady:

a. Sędzia głęboko śpi. Sędzia głęboko słucha.
b. Piękna melodia. Zielona melodia.
c. Rdza niszczy metal. Rdza podziwia metal.

Ale już nie: /zielona/ gęś \rarr  /nad/ gęś

**** Zadanie — określ kategorie syntaktyczne w zdaniu
***** Przykład 1
a) Sędzia /n/
b) przesłuchuje \(\frac{z}{nn}\)
c) świadka. /n/

***** Przykład 2
a) Nieprawda, że \(\frac{z}{z}\)
b) świeci \(\frac{z}{n}\)
c) słońce. /n/ 

*** Role semiotyczne wypowiedzi
**** Rola opisowa
Wypowiedź opisuje rzeczywistość.

a. Świeci słońce.
b. W lipcu w Polsce jest zima.

**** Rola ekspresywna
Komunikuje przeżycia, przemyślenia, stan wewnętrzny.

a. Moja poranna kawa była ekstatycznie smaczna!
b. Ach, świeci słońce!
c. Ten obraz jest przepiękny.

**** Rola sugestywna
Ma wywołać w odbiorcy komunikatu jakieś zachowanie.

a. Janku, o godz. 9 masz być w łóżku!
b. Nie jestem pewien, że podoba mi się ta twoja nowa koszulka.
d. Kto przekracza dozwoloną prędkość podlega karze…
e. Palenie zabija!

**** Rola performatywna
Wypowiedź wywołuje skutki konwencjonalne.

a. Złożenie przysięgi lub ślubowania.
b. Nakładam na Pana mandat karny w wysokości 500 zł.

***** Zadanie
Jan wypowiedział słowa przysięgi małżeńskiej wobec Małgosi, ale nie doszło do
zawarcia małżeństwa; Małgosia również wypowiedziała odpowiednie słowa, nadal nie
doszło do zawarcia małżeństwa. Dlaczego?

** FAQ

** Zadania

** Zagadka

* TODO Nazwa

** FAQ
*** Czy „zamek” (jako budynek) i „zamek” jako urządzenie montowane w drzwiach, to ta sama nazwa?
bla bla bla 

** Zadania

** Zagadka

* TODO Zdanie

** Klasyczny rachunek zdań

** FAQ

** Zadania

** Zagadka

* TODO Relacje pomiędzy przedmiotami

** FAQ

** Zadania

** Zagadka

* TODO Oceny, normy i modalności

** FAQ

** Zadania

** Zagadka
* Pytania
** Wiadomości ogólne
*Pytanie* jest rodzajem wypowiedzi, której zasadniczym zadaniem jest uzykanie informacji od adresata pytania[fn:: Inny cel może przyświecać pytaniom retorycznym mającym wywołać w adresacie tych wypowiedzi określony stan bez oczekiwania na odpowiedź. Pytania mogą być również stawiane w celu sprawdzenia wiedzy ich adresata (w kontekście dydaktycznym).]. Pytanie różni się od zdania ponieważ nie odpisuje rzeczywistości -- tym samym nie można mówić o prawdziwości bądź fałszywości pytania. Umiejętność zadawania pytań oraz oceny odpowiedzi należy do kluczowych kompetencji prawnika.

*Założeniem pytania* nazywamy zdania, które uznajemy za prawdziwe zadając dane pytanie. Przykładowo, pytanie „O której wychodzimy do kina?” przyjmuje założenie, że wychodzimy do kina. Założenie fałszywe sprawia, że mamy do czynienia z *pytaniem niewłaściwie postawionym*. Niekiedy źle postawione pytanie może skutkować odpowiedzialnością -- gdy fałszywe założenie narusza dobra prawnie chronione („W jaki sposób Pan kradnie tak ogromne sumy?” zadane osobie uczciwej); trudności może wówczas sprawiać skuteczne zasłonięcie się argumentem, że było to tylko pytanie.

Sposób postawienia pytania może wyznaczać schemat odpowiedzi na nie. Pytanie „Ile czasu zajmuje podróż samochodem z Warszawy do Łodzi?” tworzy schemat odpowiedzi w postaci „Podróż samochodem z Warszawy do Łodzi zajmuje /x/. Schemat taki nazywany jest *daną pytania* (łac. /datum quaestionis/). Pytania nieokreślające schematu odpowiedzi nazywamy *pytaniami otwartymi*.

*Niewiadomą pytania* nazywamy wyrażenie, którego podstawienie w danej pytania skutkuje otrzymaniem odpowiedzi. Niewiadomą powyższego pytania będzie zatem wyrażenie określające czas podróży samochodem z Warszawy do Łodzi. Zbiór wyrażeń możliwych do wstawienia w miejsce niewiadomej pytania nazywamy *zakresem niewiadomej pytania*. W zakresie niewiadomej pytania będą znajdować się wyrażenia takie jak „2 godziny”, „6 godzin” i „2 minuty”; zwróć jednak uwagę, że nie każda odpowiedź utworzona z wyrażenia należącego do zakresu niewiadomej pytania będzie prawdziwa. Poza zakresem niewiadomej powyższego pytania będą wyrażenia takie jak „150 km” i „dwie i pół tony” ponieważ nie można ich sensownie użyć w schemacie narzuconym przez daną pytania.

** Budowa pytań
Pytania zawierają *partykułę pytajną* (przykładowo: „kto”, „w jaki sposób”, „czy”) chociaż niekiedy należy się jej domyślić stosując reguły danego języka (np. z intonacji w języku polskim). Ze względu na użytą partykułę pytajną pytania można podzielić na:
- pytania do rozstrzygnięcia — wymagające wyboru jednej z wykluczających się odpowiedzi („Czy trójkąt mają trzy czy cztery boki?”, „Czy to prawda, że boli Cię ręka?”) oraz
- pytania do uzupełnienia — nienarzucające wyboru odpowiedzi, lecz wymagające od adresata pytania jej sformułowania („Jakie narzędzie jest najwłaściwsze dla tego zadania?”).

Niekiedy pytanie może być wadliwe ze względu na *niejednoznaczność słów* w nich użytych. Odpowiedź na pytanie „Czy nigdy nie można zrobić zbyt wiele dla ludzi starych i chorych?” będzie wymagała uprzedniego rozstrzygnięcia:
- czy chodzi o kategorię ludzi jednocześnie starych i chorych, czy też o dwie kategorie ludzi, zarówno ludzi starych jak i ludzi chorych;
- czy zwrot „nigdy nie można” oznacza negatywną ocenę nadmiernych wysiłków, czy też pozytywną ocenę podejmowania jak największych wysiłków;
- jaki poziom nakładów przekroczy próg wskazywany przez pojęcie „zbyt wiele”.
Odpowiedź „tak” albo „nie” na powyższe pytanie nie przyniesie zatem pytającemu pewnej wiedzy na temat poglądów adresata pytania.

** Odpowiedź
Rozważmy zagadnienie odpowiedzi na przykładzie pytania „Jaka miejscowość jest siedzibą Uniwersytetu Łódzkiego?”. Udzielona na dane pytanie odpowiedź może być uznana za *odpowiedź właściwą*, jeżeli powstaje ona poprzez użycie wyrażenia z zakresu niewiadomej pytania. Odpowiedziami właściwymi dla powyższego pytania będą zarówno „Siedzibą Uniwersytetu Łódzkiego jest Łódź” jak i „Siedzibą Uniwersytetu Łódzkiego jest Szczecin”. Odpowiedź właściwa nie musi być zatem prawdziwa.

Może się także zdarzyć, że wyrażenie prawdziwe będzie *odpowiedzą niewłaściwą* -- np. odpowiedź „Trójkąt ma trzy boki” na wskazane pytanie, chociaż jest zdaniem prawdziwym nie należy do zakresu niewiadomej pytania. Oczywiście, odpowiedzią niewłaściwą będzie także nieprawdziwe zdanie „Trójkąt ma pięć boków”. 

Odpowiedzi można podzielić na:
- odpowiedzi *całkowite wprost* – to odpowiedzi właściwe podążające za schematem odpowiedzi wyznaczonym przez pytanie (np. „Siedzibą Uniwersytetu Łódzkiego jest Gdańsk”),
- odpowiedzi *całkowite nie wprost* - nie podążające za schematem odpowiedzi, lecz zawierające informacje wystarczające do ustalenia odpowiedzi właściwej (np. „Siedzibą Uniwersytetu Łódzkiego jest stolica województwa łódzkiego”, „Siedzibą Uniwersytetu Łódzkiego jest miejscowość, w której urodził się Fryderyk Chopin”), 
- odpowiedzi *częściowe* - nie będąc odpowiedziami właściwymi posiadają wartość informacyjną pozwalającą wykluczyć niektóre odpowiedzi właściwe (np. „Siedzibą Uniwersytetu Łódzkiego jest pewne miasto w województwie łódzkim”).

Odpowiedzi całkowite nie wprost mogą stanowić informację o woli ukrycia prawdy. Przyjrzyj się temu dialogowi:

- pełnomocnik powoda: Czy świadek był pracownikiem pozwanego?
- świadek: Tak. -- /odpowiedź całkowita wprost/
- pełnomocnik powoda: Czy w dniu 15 czerwca 2022 r. rozpoczęli Państwo prace na budowie o godzinie wskazanej w harmonogramie robót, tj. o godzinie 8:00? 
- świadek: Zawsze robiliśmy wszystko zgodnie z harmonogramem. -- /odpowiedź całkowita nie wprost, jak się okaże za chwilę, odpowiedź jest nieprawdziwa/
- pełnomocnik powoda: Proszę odpowiedzieć odnosząc się do tego konkretnego dnia.
- świadek: Faktycznie w tym dniu wyjątkowo rozpoczęlismy pracę nieco później. -- /odpowiedź całkowita wprost, jednak sprzeczna z odpowiedzią udzieloną powyżej/

** TODO FAQ
** Zadania
1. Wskaż założenia pytania „Czy Adam jest mężem Doroty czy Anny?”.
2. Dla pytania „Jakie jest największe pod względem powierzchni państwo w Europie?” wskaż:
   a) daną pytania,
   b) niewiadomą pytania,
   c) zakres niewiadomej pytania,
   a ponadto sklasyfikuj to pytanie w ramach podziałów jakie poznałeś.
3. Ułóż pytanie i udziel na nie odpowiedzi właściwej (wprost i nie wprost) oraz odpowiedzi częściowej.

** Zagadka
Spotykasz osobę, o której wiesz, że jest prawdziwkiem albo fałszywkiem. Czy ta osoba może powiedzieć zdanie: „Jestem fałszywkiem lub trójkąt ma cztery boki”?
