#+title: Logika - notatka pomocnicza do wykładu (’24/25)
#+AUTHOR: J. Szczerbowski
#+OPTIONS: tex:t p:t
#+LANGUAGE: pl
#+STARTUP: latexpreview

* Wykład 1
SCHEDULED: <2024-10-19 Sat>
#+INCLUDE: l/00_org_w.org
#+INCLUDE: l/10_wprowadzenie.org

* Wykład 2
SCHEDULED: <2024-10-26 Sat>
#+INCLUDE: l/20_nazwy.org
  
* Wykład 3
SCHEDULED: <2024-11-23 Sat>
#+INCLUDE: l/21_stosunki.org
#+INCLUDE: l/22_definicje.org

* Wykład 4
SCHEDULED: <2024-11-23 Sat>
#+INCLUDE: l/23_podzial.org
#+INCLUDE: l/30_zdanie.org
#+INCLUDE: l/31_funktoryp.org

* Wykład 5
SCHEDULED: <2024-12-07 Sat>
#+INCLUDE: l/40_relacje.org
#+INCLUDE: l/50_oceny.org

* Wykład 6
SCHEDULED: <2024-12-14 Sat>
#+INCLUDE: l/51_modalne.org

* Wykład 7
SCHEDULED: <2025-01-11 Sat>
#+INCLUDE: l/60_pytania.org

* Wykład 8
SCHEDULED: <2025-01-18 Sat>
** Uzasadnianie bezpośrednie twierdzeń
- w jaki sposób można uznać zdanie za prawdziwe? /Postulat racji dostatecznej/ - za prawdziwe należy uznać jedynie takie zdanie, dla którego da się uzyskać należyte uzasadnienie
  + dla zdań syntetycznych - uzasadnienie opiera się na spostrzeżeniach
  + dla zdań analitycznych - uzasadnienie opiera się na regułach znaczeniowych danego języka
  + uzasadnienia pośrednie pochodzą z wnioskowania z innych zdań przyjętych uprzednio za prawdziwe
- spostrzeżenia: zewnętrzne i wewnętrzne; problem iluzji (https://www.youtube.com/watch?v=BzNzgsAE4F0)
- spostrzeżenia:
  + przypadkowe,
  + obserwacja,
  + pomiar i
  + eksperyment
** Wnioskowania niededukcyjne
*** Indukcja
Indyk filozof miał hipotezę "Człowiek jest po to, aby służyć indykom." Nastąpiło aż 1000 obserwacji potwierdzających tę hipotezę. Dnia 1001 człowiek upiekł indyka.

- Indukcja enumeracyjna:
  - S_1 jest P,
  - S_2 jest P,
  - S_3 jest P,
  - S_4 jest P,
  - S_n jest P,
  - Każde S jest P.
  - S_n - dzień, P dzień mający cechę X (np. dzień w którym człowiek służy indykowi)
- Indukcja zupełna i niezupełna.
- Indukcja eliminacyjna:
  a. kanon jednej zgodności: O_1: A, B, C, Z; O_2: C, D, E, Z; O_3: C, F, G, Z.
  b. kanon jednej różnicy:
     - O_1: A, B, C, Z;
     - O_2: B, C, Z;
     - O_3: A, C, Z;
     - O_4: A, B, ~Z.
  c. kanon zmian towarzyszących:
     - kuchenka gazowa ma palniki od 1 do 4 i 4 kurki (A…D)
     - zadanie: ustal który kurek steruje palnikiem nr 2
     - obserwacje:
       1) kurek A w poz. 50%, brak płomienia
       2) kurek A w poz. 100%, brak płomienia
       3) kurek B w poz. 50%, brak płomienia
       4) kurek B w poz. 100%, brak płomienia
       5) kurek C w poz. 50%, mały płomień
       6) kurek C w poz. 100%, duży płomień
       7) kurek D w poz. 50%, brak płomienia
       8) kurek D w poz. 100%, brak płomienia
     - wniosek: prawdopodobnie kurek C steruje płomieniem palnika nr 2.
** Wnioskowania prawnicze
- sylogizm prawniczy
  + (1) Kto zabija człowieka podlega karze. (2) Jan zabił człowieka. | Jan podlega karze.
- uzupełnianie luk w prawie; postulat zupełności kwalifikacyjnej
- argumenty prawnicze:
  + argumentum a simile (argument z podobieństwa)
    - analogia legis (analogia z ustawy)
    - analogia iuris (analogia z prawa)
  + argumentum a fortiori (jeżeli A, to tym bardziej B)
    - argumentum a maiori ad minus (argument z większego na mniejsze)
    - argumentum a miniori ad maius (argument z mniejszego na większe)
  + argumentum a contrario (argument z przeciwieństwa)
  + dyrektywa instrumentalnego nakazu i zakazu (argument z celu na środki)

*** Przykłady
- a contrario
  + Już pełnomocnik oskarżycielki posiłkowej, sporządzający apelację, dostrzegł, że doszło do przedawnienia karalności czynu z art. 284 § 2 k.k., którego upatrywał w zachowaniu oskarżonego. Takie przedawnienie tym bardziej (wcześniej) nastąpiło w stosunku do czynu z art. 284 § 1 k.k., jakiego zdaniem obecnego pełnomocnika miał się dopuścić oskarżony (zob. art. 101 § 1 pkt 4 k.k. i 102 k.k.). Przedawnienie karalności, jako okoliczność wyłączająca ściganie, wyklucza możliwość wniesienia kasacji na niekorzyść oskarżonego. Wynika to z odczytywanego a contrario przepisu art. 529 k.p.k. Kasacja już w chwili jej wniesienia okazała się więc niedopuszczalna i nie powinna być przyjęta (art. 429 § 1 k.p.k. zw. z art. 530 § 2 k.p.k. w zw. z art. 529 k.p.k. a contrario). - Postanowienie SN z 28.10.2013 r., III KK 144/13, OSNKW 2014, nr 3, poz. 22. (art. 529 k.p.k. "Wniesieniu i rozpoznaniu kasacji na korzyść oskarżonego nie stoi na przeszkodzie wykonanie kary, zatarcie skazania, akt łaski ani też okoliczność wyłączająca ściganie lub uzasadniająca zawieszenie postępowania.")
- a maiori ad minus
  + Skarżący w niniejszej sprawie ma rację, iż powód nie zgłaszał żądania obniżenia tej kary. Pozostaje zatem problem, czy Sąd może dokonać takiego miarkowania bez wyraźnego wniosku zobowiązanego. Zarówno w dawnym orzecznictwie (por. wyrok SN z 14 lipca 1976 r. I CR 271/76, OSN 1977, poz. 76, jak i w obecnym por. wyrok z 21 listopada 1996 r. I CKN 330/97 - nie publikowany) Sąd Najwyższy przyjmuje, że żądanie dłużnika oddalenia powództwa o zapłatę kary umownej mieści w sobie także jednocześnie ewentualne żądanie wnioskowania jej wysokości (rozumowanie a maiori ad minus). Sąd w składzie rozpoznającym niniejszą sprawę podziela słuszność tego stanowiska, co oznacza, że wbrew zarzutowi kasacji pozwanego - Sąd Apelacyjny mógł zmniejszyć należną mu od powoda karę umowną za odstąpienie od umowy w sytuacji, kiedy powód kwestionował w ogóle możliwości jej naliczania. - Wyrok SN z 25.03.1998 r., II CKN 660/97, LEX nr 519952.
- a minori ad maius
  + Skoro wady uzasadnienia wyroku sądu odwoławczego polegające na naruszeniu art. 457 § 3 k.p.k. stanowić mogą podstawę uchylenia tego wyroku, to a minori ad maius podstawę taką stanowić może całkowity brak uzasadnienia. - Wyrok SN z 8.09.2005 r., II KK 373/04, OSNwSK 2005, nr 1, poz. 1615.
- a simile
  + Nie bez znaczenia jest fakt, że strony w tym czasie miały do siebie zaufanie, razem zamieszkiwały i mogły posiadać w domu własne i wspólne (w ramach konkubinatu - por. art. 860 k.c. a simile i następne) środki finansowe a także fakt, że powódka w tym okresie była uprawniona do dokonywania operacji finansowych na kontach pozwanego (bezsporne). - Wyrok SR w Olsztynie z 12.12.2017 r., I C 1882/17, LEX nr 2432212.
* Wykład 9
SCHEDULED: <2025-01-25 Sat>
** Nieporozumienia
- wieloznaczność słów:
  + Każdy ssak lubiący jeść pączki, lubi chodzić do cukierni. Łoś lubi jeść pączki. A więc, łoś lubi chodzić do cukierni.
  + znaczenie aktualne i znaczenie potencjalne: Czy Tadek gra w brydża?
- błąd ekwiwokacji: użycie tego samego słowa w różnych znaczeniach; szczególne znaczenie w przypadku mowy prawniczej
- wieloznaczność wypowiedzi złożonej: Nigdy nie można zrobić zbyt wiele dla ludzi starych i chorych.
- znaczenie dosłowne i niedosłowne: /Człowiek człowiekowi wilkiem./
- skróty myślowe: /Mniej znaczy więcej./
-  Amfibologia- wypowiedź wieloznaczna ze względu na składnię: /Paweł powiedział swojej koleżance, że ona jest niemądra./

** Dedukcja
- wnioskowanie jako proces myślowy, przesłanki, przesłanki entymematyczne
  + przykłady wnioskowań:
    - Kto zabija zwierzęta ten ma predyspozycje do mordowania ludzi.
    - Jest piątek, a więc czas na pizzę.
    - Kto sprzedaje narkotyki jest dealerem.
    - Kto zażywa narkotyki ten jest dealerem.
    - Jan prowadzi samochód kompletnie pijany, a więc Jan podlega karze.
    - Jest sobota, a więc czas na kuchnię hinduską.
    - Jestem ubogi, a więc idę do pracy.
    - Jeśli zauważam wzrastające temperatury co roku, to znaczy, że następuje ocieplenie klimatu.
    - Wschodzi krwawe słońce a więc przelano krew tej nocy.
- wnioskowania zawodne i wnioskowania niezawodne (/Każdy człowiek jest śmiertelny. Sokrates jest człowiekiem. A więc, Sokrates jest śmiertelny./)
- prawa logiki
  + prawo transpozycji: (p \sup q) \sup (\sim q \sup \sim p): Jeżeli (Jeżeli pada deszcz, to ulica jest mokra) to (Jeżeli nieprawda, że ulica jest mokra to nieprawda, że pada deszcz)
  + prawo kontrapozycji: \prod S,P: SaP \equiv nie-S a nie-P
- sylogizm: /Ponieważ (1) jeżeli p, to q i (2) jeżeli q, to r (3) to jeżeli p to r./
  + [ (p \sup q) \cdot (q \sup r)] \sup (p \sup r)
  + [(p \sup q) \cdot p] \sup q (modus ponendo ponens): Jeżeli [(Jeżeli woda wrze to jest gorąca) i woda wrze] to woda jest gorąca
  + [(p \sup q) \cdot \sim q] \sup \sim p (modus tollendo tollens): /Jeżeli [(Jeżeli woda wrze to jest gorąca) i nieprawda, że woda jest gorąca] to nieprawda, że woda wrze./
  + [(p \vee q) \cdot \sim p] \sup q (modus tollendo ponens): /Jeżeli [(Wicked jest psem lub Wicked jest kotem) i nieprawda, że Wicked jest kotem] to Wicked jest psem./

- sylogistyka Arystotelesa
  + zdania w postaci:
  + zd. ogólno-twierdzące:     SaP - /każde S jest P/
  + zd. ogólno-przeczące:      SeP - /żadne S nie jest P/
  + zd. szczególno-twierdzące: SiP - /istnieją S, które są P/
  + zd. szczególno-przeczące:  SoP - /istnieją S, które są nie-P/
  + SaP \equiv \sim (SoP)
  + SeP \equiv \sim (SiP)
  + SiP \equiv \sim (SeP)
  + SoP \equiv \sim (SaP)

#+begin_verse

MaP
SiM
------
SiP

Każdy adwokat jest prawnikiem.
Niektórzy ludzie są adwokatami.
------
Niektórzy ludzie są prawnikami.

Każdy polityk jest gadem.
Niektórzy profesorowie są politykami.
------
Niektórzy profesorowie są gadami.

#+end_verse

FIFO - first in first out, FILO - first in last out, GIGO - garbage in garbage out

* Wykład 10
SCHEDULED: <2025-02-01 Sat>
** Zerówka
- 10 pytań
- forma: test na Teams
- pytania: zamknięte, jednokrotnego i wielokrotnego wyboru
- 10 minut na uzupełnienie
- po rozpoczęciu obowiązuje absolutna cisza

** Myślenie kierowane z góry postawionymi zadaniami
- myślenie spontaniczne, a myślenie kierowane z góry postanowionymi zadaniami
- zadania:
  + zadania rozstrzygnięcia: „czy prawdą jest, że p”?
  + zadania wyjaśnienia: „dlaczego prawdą jest, że p”?
- dowodzenie
  + dowodzenie a wiadomości o świecie
  + dowodzenie wprost: wiadomo, że jeśli p to q; wiadomo, że p, a więc udowodnione jest, że q
    + jeżeli w pomieszczeniu są czyjeś odciski palców, to ta osoba była w tym pomieszczeniu
  + dowodzenie nie wprost: przypuszczam, że \sim{}q; wiem, że jeżeli \sim{}q to r; wiem, że ~r; a więc wiem, że \sim{}\sim{}q czyli q
  + błędy w dowodzeniu:
    - błąd materialny, bład formalny, błąd petitio principi
    - błąd błędnego koła  - 
    - nieznajomość tezy dowodzonej - ignoratio elenchi 
- sprawdzanie
  + czy p?
    - wiem, że p \sup q
    - (a) wiem, że q: a więc?
    - (b) wiem, że \sim{}q: a więc?
- wyjaśnianie
  + dlaczego jest tak a tak?
  + hipoteza wyjaśniająca (np. hipoteza samorództwa, hipoteza flogistonu)
** Prawdopodobieństwo
- zagadka Monty Hall
- prawdopodobieństwo a ryzyko
- *Prawdopodobieństwo* ma różne znaczenia:
  - psychologiczne — siła przekonania o pewności danego zdania
  - logiczne (metodologiczne) — istnieją podstawy statystyczne (lub wynikające z innych metod) do uznania zdania za prawdziwe

Przed i po:    
- *prawodpodobieństwo aprioryczne*
- *prawodpodobieństwo aposterioryczne*

** Implikatura
- *Piotr*: Czy wszystko w porzadku? *Katarzyna*: Tak, po prostu się odczep ode mnie ty nieczuły filistynie. Wniosek: Wszystko jest OK, Piotr może otworzyć piwo i oglądać mecz; status Katarzyny jest bardzo dobry.
- *Piotr*: Znalazłem super wycieczkę, idę do szefa po urlop i jedziemy z Kasią na Maltę. *Wojciech*: Pojedziecie to wy na księżyc. Jaki wniosek powinien wyciągnąć Piotr?

**** Zasady współpracy
Twoja wypowiedź powinna wnosić oczekiwany wkład do wymiany zdań.

1. Nie wygłaszaj poglądów fałszych ani nawet niedostatecznie uzasadnionych (maksyma jakości).
2. Nie udzielaj zbyt wiele, ani zbyt mało informacji (maksyma ilości).
3. Nie wypowiadaj słów irrelewantnych (maksyma istotności).
4. Mów w sposób zrozumiały (maksyma sposobu).

Jan: Która jest godzina? Elżbieta: Przecież wiesz, o której jemy obiad.

** Umiejętność przekonywania
 - agrumentowanie to czynność polegającu na wywołaniu adresata wypowiedzi określonego przeświadczenia
 - nie zawsze argument musi być rozsądny \rarr wszystko zależy od adresata
 - zarzuty w dyskusji:
   - merytoryczne, materialne
   - formalne
 - fortele erystyczne
   - argumentum ad personam
   - argumentum ad populum
   - argumentum ad vanitatem
   - argumentum ad misericordiam
 - problem argumentu z autorytetu
   
* ŚCIĄGA: Symbole logiczne
W nawiasach oznaczono alternatywne symbole.

- Kwantyfikator ogólny: \prod x (\forall)
- Kwantyfikator szczegółowy: \sum{} x (\exists)
- Negacja: \sim{}p (\neg{}p)
- Koniunkcja: p \cdot q (p \wedge q; Kpq; p & q; &&)
- Implikacja: p \sup q (p \to  q)
- Alternatywa nierozłączna: p \vee q (p + q; Apq; ||)
- Alternatywa rozłączna: p \perp q
- Dysjunkcja: p / q
- Binegacja: p \downarrow q
- Równoważność: p \equiv q (p \harr  q)
- Konieczność: \(\Box{}p\)
- Możliwość: \(\diamond{}p\)
 	◻
- 
\plus 
